### ISSUE TITLE
Search box is disappeared when a keyword couldn't find in a item list.

### ISSUE THREAD

**Issue by y16i** [softsimon/ngx-bootstrap-multiselect#470]
[Steps]
1. Click "Select"
2. Type "A" in a search box

[Result]
It shows "Nothing found..." and the search box is disappeared. It doesn't show up until reload the page.

[Stackblitz]
https://stackblitz.com/edit/angular-p8e4nd

[Note]
ss-multi... was ok. I don't know when it start happening.

**Comment by giannidhooge** [comment]
Fixed by https://github.com/softsimon/ngx-bootstrap-multiselect/pull/469 but waiting for a review/merge.

**Comment by softsimon** [comment]
Merged and published new version
