### ISSUE TITLE
[feat] Update to Angular 14

### ISSUE THREAD

**Issue by sommmen** [softsimon/ngx-bootstrap-multiselect#482]
Hiya @softsimon,

The component works as-is on Angular 14, but ofcourse i'm now getting a bunch of errors:

``` 
PS C:\Repos\Front-End> npm install        
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: ngx-bootstrap-multiselect@2.1.1
npm ERR! Found: @angular/common@14.2.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.2.1" from the root project
npm ERR!   peer @angular/common@"^14.0.0 || ^15.0.0" from @angular/cdk@14.2.1
npm ERR!   node_modules/@angular/cdk
npm ERR!     @angular/cdk@"^14.2.1" from the root project
npm ERR!   9 more (@angular/forms, @angular/platform-browser, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^10.0.6" from ngx-bootstrap-multiselect@2.1.1
npm ERR! node_modules/ngx-bootstrap-multiselect
npm ERR!   ngx-bootstrap-multiselect@"^2.1.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@10.2.5
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^10.0.6" from ngx-bootstrap-multiselect@2.1.1
npm ERR!   node_modules/ngx-bootstrap-multiselect
npm ERR!     ngx-bootstrap-multiselect@"^2.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\[REDACTED]\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[REDACTED]\AppData\Local\npm-cache\_logs\2022-09-15T07_34_52_319Z-debug-0.log
```

This is forcing me to use `--force` when running `npm install` to make the project work.
Could this please be updated to the latest Angular version?

I'll be happy to shoot in a PR - i'm not JS dev, but this seems like an easy task. 
Just let me know.

**Comment by softsimon** [comment]
> I'll be happy to shoot in a PR

I would be happy to merge it ;)

**Comment by sommmen** [comment]
> > I'll be happy to shoot in a PR
> 
> I would be happy to merge it ;)


K - I hope someone who's an actual js dev could chip in but ill try and make a PR if i can find some time.
Would it be a good idea to make packages for angular versions inbetween or should we move directly to v14?


@kek-Sec FYI perhaps you'd wanna help.

**Comment by kek-Sec** [comment]
I'd be down to give this a try , tbh this project's deps have stayed quite a bit behind

**Comment by sommmen** [comment]
> I'd be down to give this a try , tbh this project's deps have stayed quite a bit behind

Go for it if you have the time 😄. I got holiday coming up so before i have any time it will be a while.

**Comment by sommmen** [comment]
> I'd be down to give this a try , tbh this project's deps have stayed quite a bit behind

Bump. Do you reckon you have some time to update to v14?
v15 is out aswell, but personally i'm stuck in v14 for a while due to other libraries.

**Comment by bertdewolf** [comment]
Any update on the status of upgrading to angular v14?

I'm trying to use it but I'm getting: NgxBootstrapMultiselectModule does not have a module def (ɵmod property)

**Comment by dsteegen** [comment]
@softsimon 
I created the following PR: https://github.com/softsimon/ngx-bootstrap-multiselect/pull/485
This should make the library compatible with Angular 15. I hope you have time to have a look at it.

**Comment by dsteegen** [comment]
@softsimon thank you merging my PR already :D I didn't expect that you would approve it so fast!
May I assume that you will also release a new version to the public NPM repository anytime soon? ;)

**Comment by sommmen** [comment]
Latest v on npm saids;

 "peerDependencies": {
    "@angular/common": ">=15.0.0",
    "@angular/core": ">=15.0.0"
  },
  
So this has long been done :). Updating now!
